ePizzaHub.WebUI/Areas/User/Controllers/DashboardController.cs
using ePizzaHub.WebUI.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ePizzaHub.WebUI.Areas.User.Controllers
{
    public class DashboardController : BaseController
    {
        public DashboardController(IUserAccessor userAccessor) : base(userAccessor)
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

ePizzaHub.WebUI/Areas/User/Controllers/OrderController.cs
using ePizzaHub.Entities;
using ePizzaHub.Repositories.Models;
using ePizzaHub.Services.Interfaces;
using ePizzaHub.WebUI.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ePizzaHub.WebUI.Areas.User.Controllers
{
    public class OrderController : BaseController
    {
        private IOrderService _orderService;

        public OrderController(IOrderService orderService, IUserAccessor userAccessor) : base(userAccessor)
        {
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            IEnumerable<Order> orders = _orderService.GetUserOrders(CurrentUser.Id);
            return View(orders);
        }

        [Route("~/User/Order/Details/{OrderId}")]
        public IActionResult Details(string OrderId)
        {
            OrderModel Order = _orderService.GetOrderDetails(OrderId);
            return View(Order);
        }
    }
}

ePizzaHub.WebUI/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 mb-2">
                <div class="mb-4">
                    <h3>ePizza Hub</h3>
                    <p class="text-justify">There is something for everyone here. The vegetarians, non-vegetarians, the sides lovers to have something sweet by the time they reach the last bite of the last slice of pizza slice.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                <div class="mb-4 ml-md-4">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-1">About Us</a></li>
                        <li><a href="#" class="py-1">Contact Us</a></li>
                        <li><a href="#" class="py-1">Terms & Conditions</a></li>
                        <li><a href="#" class="py-1">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-2">
                <div class="mb-4">
                    <h3>Have a Questions?</h3>
                    <div class="mb-3">
                        <ul class="list-unstyled">
                            <li class="py-1"><i class="bi bi-geo-alt"></i>  C57, Sector-2, Noida 201301</li>
                            <li class="py-1"><a href="#"><i class="bi bi-phone"></i> +91- 999 9123 502</a></li>
                            <li class="py-1"><a href="#"><i class="bi bi-envelope"></i> info@epizzahub.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                Copyright © @DateTime.Now.Year | All rights reserved | This website is made with <i class="bi bi-heart" aria-hidden="true"></i> by <a href="https://dotnettricks.com" target="_blank">www.dotnettricks.com</a>
            </div>
        </div>
    </div>
</footer>

ePizzaHub.WebUI/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" style="height:40px" class="d-inline-block mb-1" /> <span class="d-inline-block">ePizzaHub</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Menu</a>
                    </li>
                </ul>
                <partial name="_UserMenu" />
            </div>
        </div>
    </nav>
</header>

ePizzaHub.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ePizzaHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <partial name="_Header" />
    <div class="container">
        <main role="main" class="pb-4 pt-4">
            @RenderBody()
        </main>
    </div>
    <partial name="_footer" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/cart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ePizzaHub.WebUI/Views/Shared/_PizzaMenu.cshtml
<div class="container pb-4">
    <div class="row pt-4">
        <h2 class="mb-4 col-sm-12" id="heading">Pizza, Dessert and Beverages</h2>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4 pb-4">
                <div class="card box-shadow">
                    <img class="card-img-top" src="@item.ImageUrl" alt="image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">@item.Name <span class="float-right font-20">₹@item.UnitPrice.ToString("##.#")</span></h4>
                        <p class="card-text">@item.Description</p>
                        <p>
                            <span class="pt-1 d-inline-block"> Size: Regular</span>
                            <span class="float-right font-20">
                                <a href="javascript:void(0)" onclick="AddToCart('@item.Id','@item.Name','@item.UnitPrice',1)" class="btn btn-outline-primary">Add To Cart</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="toast fade hide" data-autohide="false" id="toastCart">
    <div class="toast-header">
        <strong class="mr-auto text-primary">Notification</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">×</button>
    </div>
    <div class="toast-body"></div>
</div>

ePizzaHub.WebUI/Views/Shared/_PublicLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/cart.js"></script>
</head>
<body>
    <partial name="_Header" />
    <div>
        @RenderBody()
    </div>
    <partial name="_footer" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ePizzaHub.WebUI/Views/Shared/_UserMenu.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index"> <span class="noti_Counter">0</span> <i class="bi bi-cart"></i></a>
    </li>
    @if (CurrentUser != null)
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Welcome : @CurrentUser.Name
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-action="Index" asp-controller="Dashboard" asp-area="User">Dashboard</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="Order" asp-area="User">My Orders</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Account" asp-area="" asp-action="Logout">LogOut</a>
            </div>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">SignUp</a>
        </li>
    }
</ul>