ePizzaHub.WebUI/Controllers/HomeController.cs
using ePizzaHub.Entities;
using ePizzaHub.Services.Interfaces;
using ePizzaHub.WebUI.Extensions;
using ePizzaHub.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace ePizzaHub.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ICatalogService _catalogService;
        private IMemoryCache _cache;
        private IDistributedCache _distributedCache;

        public HomeController(ILogger<HomeController> logger, ICatalogService catalogService, IMemoryCache cache, IDistributedCache distributedCache)
        {
            _catalogService = catalogService;
            _logger = logger;
            _cache = cache;
            _distributedCache = distributedCache;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Item> itemList = await LoadItems();
           //var itemList = _catalogService.GetItems();
            return View(itemList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult PrivacyPolicy()
        {
            return View("Privacy");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task<IEnumerable<Item>> LoadItems()
        {
            IEnumerable<Item> listItems = null;
            string recordKey = "ItemList";

            listItems = await _distributedCache.GetRecordAsync<IEnumerable<Item>>(recordKey);

            if (listItems is null)
            {
                listItems = _catalogService.GetItems();

                await _distributedCache.SetRecordAsync(recordKey, listItems);
            }

            return listItems;
        }
    }
}

ePizzaHub.WebUI/ViewComponents/PizzaMenuViewComponent.cs
using ePizzaHub.Entities;
using ePizzaHub.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ePizzaHub.WebUI.ViewComponents
{
    public class PizzaMenuViewComponent : ViewComponent
    {
        private ICatalogService _catalogService;

        public PizzaMenuViewComponent(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        public IViewComponentResult Invoke()
        {
            //string key = "catalogs";
            //var itemList = _cache.GetOrCreate(key, (entry) =>
            //{
            //    entry.AbsoluteExpiration = DateTime.Now.AddHours(24);
            //    entry.SlidingExpiration = TimeSpan.FromMinutes(15);
            //    entry.Priority = CacheItemPriority.Normal;

            //    var data = _catalogService.GetItems();
            //    return data;
            //});

            IEnumerable<Item> itemList = _catalogService.GetItems();
            return View("/views/shared/_PizzaMenu.cshtml", itemList);
        }
    }
}

ePizzaHub.WebUI/Views/Home/Index.cshtml
@model IEnumerable<Item>

@{
    ViewData["Title"] = "ePizza Hub";
    Layout = "_PublicLayout";
}
<div style="background:#1a5ca3;">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 text-white" style="width:100%">
                <div class="pt-5 pb-5">
                    <h1>ePizza Hub's Online Ordering</h1>
                    <p class="pb-4">
                        Yummy pizza delivered fast at your door step!
                    </p>
                    <p>
                        <a href="#heading" class="btn btn-success">ORDER ONLINE NOW</a>
                    </p>
                </div>
            </div>
            <div class="col-sm-4 pt-4">
                <img src="~/images/pizza-header.png" class="img-fluid" />
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("PizzaMenu")